/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentWalletRouteImport } from './routes/agent-wallet'
import { Route as AuthorizeRouteImport } from './routes/authorize'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as GitbookRouteImport } from './routes/gitbook'
import { Route as PitchRouteImport } from './routes/pitch'
import { Route as ProtocolsRouteImport } from './routes/protocols'
import { Route as DocsPageRouteImport } from './routes/docs_.$page'
import { Route as GitbookPageRouteImport } from './routes/gitbook_.$page'
import { Route as PitchPrintRouteImport } from './routes/pitch_.print'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentWalletRoute = AgentWalletRouteImport.update({
  id: '/agent-wallet',
  path: '/agent-wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizeRoute = AuthorizeRouteImport.update({
  id: '/authorize',
  path: '/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const GitbookRoute = GitbookRouteImport.update({
  id: '/gitbook',
  path: '/gitbook',
  getParentRoute: () => rootRouteImport,
} as any)
const PitchRoute = PitchRouteImport.update({
  id: '/pitch',
  path: '/pitch',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolsRoute = ProtocolsRouteImport.update({
  id: '/protocols',
  path: '/protocols',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsPageRoute = DocsPageRouteImport.update({
  id: '/docs_/$page',
  path: '/docs/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const GitbookPageRoute = GitbookPageRouteImport.update({
  id: '/gitbook_/$page',
  path: '/gitbook/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const PitchPrintRoute = PitchPrintRouteImport.update({
  id: '/pitch_/print',
  path: '/pitch/print',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-wallet': typeof AgentWalletRoute
  '/authorize': typeof AuthorizeRoute
  '/builder': typeof BuilderRoute
  '/docs': typeof DocsRoute
  '/gitbook': typeof GitbookRoute
  '/pitch': typeof PitchRoute
  '/protocols': typeof ProtocolsRoute
  '/docs/$page': typeof DocsPageRoute
  '/gitbook/$page': typeof GitbookPageRoute
  '/pitch/print': typeof PitchPrintRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-wallet': typeof AgentWalletRoute
  '/authorize': typeof AuthorizeRoute
  '/builder': typeof BuilderRoute
  '/docs': typeof DocsRoute
  '/gitbook': typeof GitbookRoute
  '/pitch': typeof PitchRoute
  '/protocols': typeof ProtocolsRoute
  '/docs/$page': typeof DocsPageRoute
  '/gitbook/$page': typeof GitbookPageRoute
  '/pitch/print': typeof PitchPrintRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-wallet': typeof AgentWalletRoute
  '/authorize': typeof AuthorizeRoute
  '/builder': typeof BuilderRoute
  '/docs': typeof DocsRoute
  '/gitbook': typeof GitbookRoute
  '/pitch': typeof PitchRoute
  '/protocols': typeof ProtocolsRoute
  '/docs_/$page': typeof DocsPageRoute
  '/gitbook_/$page': typeof GitbookPageRoute
  '/pitch_/print': typeof PitchPrintRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-wallet'
    | '/authorize'
    | '/builder'
    | '/docs'
    | '/gitbook'
    | '/pitch'
    | '/protocols'
    | '/docs/$page'
    | '/gitbook/$page'
    | '/pitch/print'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-wallet'
    | '/authorize'
    | '/builder'
    | '/docs'
    | '/gitbook'
    | '/pitch'
    | '/protocols'
    | '/docs/$page'
    | '/gitbook/$page'
    | '/pitch/print'
  id:
    | '__root__'
    | '/'
    | '/agent-wallet'
    | '/authorize'
    | '/builder'
    | '/docs'
    | '/gitbook'
    | '/pitch'
    | '/protocols'
    | '/docs_/$page'
    | '/gitbook_/$page'
    | '/pitch_/print'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentWalletRoute: typeof AgentWalletRoute
  AuthorizeRoute: typeof AuthorizeRoute
  BuilderRoute: typeof BuilderRoute
  DocsRoute: typeof DocsRoute
  GitbookRoute: typeof GitbookRoute
  PitchRoute: typeof PitchRoute
  ProtocolsRoute: typeof ProtocolsRoute
  DocsPageRoute: typeof DocsPageRoute
  GitbookPageRoute: typeof GitbookPageRoute
  PitchPrintRoute: typeof PitchPrintRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-wallet': {
      id: '/agent-wallet'
      path: '/agent-wallet'
      fullPath: '/agent-wallet'
      preLoaderRoute: typeof AgentWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authorize': {
      id: '/authorize'
      path: '/authorize'
      fullPath: '/authorize'
      preLoaderRoute: typeof AuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gitbook': {
      id: '/gitbook'
      path: '/gitbook'
      fullPath: '/gitbook'
      preLoaderRoute: typeof GitbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pitch': {
      id: '/pitch'
      path: '/pitch'
      fullPath: '/pitch'
      preLoaderRoute: typeof PitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocols': {
      id: '/protocols'
      path: '/protocols'
      fullPath: '/protocols'
      preLoaderRoute: typeof ProtocolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs_/$page': {
      id: '/docs_/$page'
      path: '/docs/$page'
      fullPath: '/docs/$page'
      preLoaderRoute: typeof DocsPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gitbook_/$page': {
      id: '/gitbook_/$page'
      path: '/gitbook/$page'
      fullPath: '/gitbook/$page'
      preLoaderRoute: typeof GitbookPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pitch_/print': {
      id: '/pitch_/print'
      path: '/pitch/print'
      fullPath: '/pitch/print'
      preLoaderRoute: typeof PitchPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentWalletRoute: AgentWalletRoute,
  AuthorizeRoute: AuthorizeRoute,
  BuilderRoute: BuilderRoute,
  DocsRoute: DocsRoute,
  GitbookRoute: GitbookRoute,
  PitchRoute: PitchRoute,
  ProtocolsRoute: ProtocolsRoute,
  DocsPageRoute: DocsPageRoute,
  GitbookPageRoute: GitbookPageRoute,
  PitchPrintRoute: PitchPrintRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
